name: CI

on:
    push:
        branches: ['[0-9]+-*']

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run NPM install
          run: |
            npm install
        - name: Run type-checking
          run: |
            npm run type-check
        - name: Run eslint
          run: |
            npm run lint
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Clone deps
              run: |
                mkdir deps
                cd deps
                mkdir temp
                echo "Cloning NativeUILua"
                git clone -b 1-js-support https://github.com/tomezpl/NativeUILua.git temp/NativeUILua
                echo "Extracting NativeUI code from NativeUILua repo"
                cp -r temp/NativeUILua/NativeUI NativeUI
                echo "Cloning alertbox"
                git clone https://github.com/tomezpl/alertbox alertbox
                echo "Cleaning up"
                rm -r temp
                cd ../
                git submodule update --init --recursive
            - name: Install NPM deps
              run: |
                npm install
            - name: Build
              run: |
                npm run build
            - name: Package
              run: |
                mkdir build
                mkdir build/lbg-char-neo
                cp fxmanifest.lua build/lbg-char-neo
                cp -r assets build/lbg-char-neo/assets
                cp -r dist build/lbg-char-neo/dist
                cp -r deps/* build
            - name: Upload build artifact
              uses: actions/upload-artifact@v4
              with:
                name: build
                path: build